### PR TITLE
Allow users to define crop ratio 

### PR DESCRIPTION
**Pull request by moa-novae**
I added a ratio prop to ImageManipulator.
When users change the size of the crop mask by dragging, the mask dimensions will self adjust so the specified ratio is respected.  

This is my first time doing PRs, so if there is anything I missed, please let me know. I've just started coding recently.

### CODE REVIEW

**Comment by brunon80** [comment]
Thanks for this PR, I will analyze and if everything is ok I will merge!

**Comment by moa-novae** [comment]
After playing around a bit more, I realized that the crop box isn't behaving in the nicest way when a ratio is specified. I will try to address this.

**Comment by kushalsogani** [comment]
Hi @brunon80 and @moa-novae . This PR is the most useful feature for this package as iOS doesn't allow to crop apart from square. The masked prop also is not sufficient because we cannot zoom in and out of an image. Could you please provide an update on this? Thanks!!

**Comment by brunon80** [comment]
Merged!

**Comment by moa-novae** [comment]
Hi, @kushalsogani, when a ratio is specified, the crop mask never behaved as smooth as I would've liked. I played around a bit, but couldn't fix it. Could you take a look at it, and provide some suggestions? When I have time, I would be happy to come back to it.

**Pull request merged**
